name: "Terraform - Ejecución Manual"

# 'workflow_dispatch' activa el botón manual en la interfaz de GitHub
on:
  workflow_dispatch:
    inputs:
      grupo:
        description: 'Selecciona el grupo de repositorios a gestionar'
        required: true
        type: choice
        options:
          - grupo-devops
      accion:
        description: '¿Qué acción deseas ejecutar?'
        required: true
        type: choice
        default: 'plan'
        options:
          - plan
          - apply

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform: ${{ github.event.inputs.grupo }} (${{ github.event.inputs.accion }})"
    runs-on: ubuntu-latest

    # Obliga a Terraform a pararse dentro de la carpeta del grupo seleccionado
    defaults:
      run:
        working-directory: grupos/${{ github.event.inputs.grupo }}

    steps:
      - name: Checkout Código
        uses: actions/checkout@v6

      - name: 🗝️ Generar Token de acceso de GitHub App
        id: get_app_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.GIT_TOKEN_NORMALIZA_DEVOPS_CODE_APP_ID }}
          private-key: ${{ secrets.GIT_TOKEN_NORMALIZA_DEVOPS_CODE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      
      - name: ⚙️ Cargar Variables de Entorno Globales
        run: |
          echo "GITHUB_TOKEN=${{ steps.get_app_token.outputs.token }}" >> $GITHUB_ENV
          echo "GITHUB_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # Se ejecuta solo si elegiste 'plan'
      - name: Terraform Plan
        if: ${{ github.event.inputs.accion == 'plan' }}
        run: terraform plan

      # Se ejecuta solo si elegiste 'apply'
      - name: Terraform Apply
        if: ${{ github.event.inputs.accion == 'apply' }}
        run: terraform apply -auto-approve